# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec file for building macOS .app bundle
# - Bundles ChromeDriver; users need Google Chrome installed (no Python/Selenium needed)
# - Produces a proper macOS GUI .app (windowed, with Qt plugins + qt.conf)
#
# Prerequisites (run once before building):
#   python resources/download_chromedriver.py
#
# Usage:
#   source venv/bin/activate
#   pyinstaller ZaloGroupChecker.spec --noconfirm

from pathlib import Path
from PyInstaller.utils.hooks import collect_all

block_cipher = None

# -----------------------------------------------------------------------
# Collect EVERYTHING from PyQt6 (binaries, data files, hidden imports).
# This is what ships:
#   - platforms/libqcocoa.dylib  (Qt platform plugin)
#   - imageformats/, styles/, iconengines/, ...
#   - qt.conf (auto-generated by PyInstaller, points Qt at plugins dir)
#   - Qt6 frameworks (QtCore, QtGui, QtWidgets, ...)
# Without this, app crashes at launch with:
#   "Could not find the Qt platform plugin 'cocoa'"
# -----------------------------------------------------------------------
pyqt6_datas, pyqt6_binaries, pyqt6_hiddenimports = collect_all('PyQt6')

# -----------------------------------------------------------------------
# Bundle the ChromeDriver binary
# -----------------------------------------------------------------------
chromedriver_dir = Path('resources/chromedriver')
chromedriver_binaries = []

if chromedriver_dir.exists():
    for f in chromedriver_dir.iterdir():
        if f.is_file():
            chromedriver_binaries.append((str(f), 'chromedriver'))
    print(f"[INFO] Bundling ChromeDriver from: {chromedriver_dir}")
else:
    print("[WARNING] resources/chromedriver/ not found.")
    print("          Run: python resources/download_chromedriver.py")

# -----------------------------------------------------------------------
# Entitlements (used by --codesign step in workflow, and BUNDLE)
# -----------------------------------------------------------------------
entitlements_path = 'resources/entitlements.plist'
entitlements_file = entitlements_path if Path(entitlements_path).exists() else None

# -----------------------------------------------------------------------
# Icon
# -----------------------------------------------------------------------
icon_path = 'resources/icon.icns' if Path('resources/icon.icns').exists() else None

a = Analysis(
    ['src/main.py'],
    pathex=['src'],
    binaries=chromedriver_binaries + pyqt6_binaries,
    datas=[
        ('config.json', '.'),
        ('resources', 'resources'),
    ] + pyqt6_datas,
    hiddenimports=[
        # PyQt6 extras (collect_all already covers this, keep as safety net)
        'PyQt6',
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'PyQt6.sip',
        # Selenium
        'selenium',
        'selenium.webdriver',
        'selenium.webdriver.chrome',
        'selenium.webdriver.chrome.service',
        'selenium.webdriver.chrome.options',
        'selenium.webdriver.common.by',
        'selenium.webdriver.support.ui',
        'selenium.webdriver.support.expected_conditions',
        'selenium.webdriver.support',
        'selenium.common.exceptions',
        # webdriver-manager (fallback when running from source)
        'webdriver_manager',
        'webdriver_manager.chrome',
        # Data processing
        'pandas',
        'pandas._libs.tslibs.timedeltas',
        'pandas._libs.tslibs.np_datetime',
        'pandas._libs.tslibs.nattype',
        'pandas._libs.skiplist',
        'openpyxl',
        'openpyxl.workbook',
        'openpyxl.styles',
        'openpyxl.utils',
        'xlrd',
        # Fuzzy matching
        'fuzzywuzzy',
        'fuzzywuzzy.fuzz',
        'fuzzywuzzy.process',
        'Levenshtein',
        # Helpers
        'pkg_resources',
        'charset_normalizer',
        'encodings.utf_8',
        'encodings.ascii',
        'encodings.latin_1',
    ] + pyqt6_hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'scipy',
        'IPython',
        'jupyter',
        'playwright',
        # Avoid Qt6 alternatives clashing with PyQt6
        'PyQt5',
        'PySide2',
        'PySide6',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ZaloGroupChecker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    # UPX MUST be disabled on macOS — it corrupts signed .dylib/.framework
    # and causes silent crashes ("damaged, move to Trash") via Gatekeeper.
    upx=False,
    # GUI app — NO terminal. If True, macOS builds a CLI binary wrapped in
    # a fake .app and CFBundleCopyBundleURL fails at launch.
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    # None => build native to host arch. Do NOT force 'arm64' unless you are
    # sure all users are on Apple Silicon; otherwise Intel Macs crash instantly.
    # Set to 'universal2' only if every dep (incl. Levenshtein, pandas wheels)
    # ships universal2 wheels — otherwise build will fail.
    target_arch=None,
    codesign_identity=None,
    entitlements_file=entitlements_file,
    icon=icon_path,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,            # See note above — never UPX on macOS
    upx_exclude=[],
    name='ZaloGroupChecker',
)

app = BUNDLE(
    coll,
    name='ZaloGroupChecker.app',
    icon=icon_path,
    bundle_identifier='com.zalogroupchecker.app',
    info_plist={
        'CFBundleName': 'Zalo Group Checker',
        'CFBundleDisplayName': 'Zalo Group Checker',
        'CFBundleExecutable': 'ZaloGroupChecker',
        'CFBundleVersion': '1.0.0',
        'CFBundleShortVersionString': '1.0.0',
        'CFBundlePackageType': 'APPL',
        'CFBundleSignature': '????',
        'CFBundleInfoDictionaryVersion': '6.0',
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '11.0',
        'LSApplicationCategoryType': 'public.app-category.productivity',
        'NSHumanReadableCopyright': 'Copyright \u00a9 2026',
        'LSFileQuarantineEnabled': False,
        # Needed so Selenium can drive Chrome via AppleEvents on macOS 10.14+
        'NSAppleEventsUsageDescription':
            'Zalo Group Checker uses Google Chrome to access zalo.me.',
        'NSAppTransportSecurity': {
            'NSAllowsArbitraryLoads': True,
        },
        'CFBundleDocumentTypes': [
            {
                'CFBundleTypeName': 'Excel File',
                'CFBundleTypeRole': 'Viewer',
                'LSItemContentTypes': [
                    'org.openxmlformats.spreadsheetml.sheet',
                    'com.microsoft.excel.xls',
                ],
            }
        ],
    },
)
